### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by jvtradingren** [SamurAIGPT/AI-Youtube-Shorts-Generator#12]
Traceback (most recent call last):
  File "/Users/ffreodasilva/Downloads/AI-Youtube-Shorts-Generator/main.py", line 23, in <module>
    start , stop = GetHighlight(TransText)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ffreodasilva/Downloads/AI-Youtube-Shorts-Generator/Components/LanguageTasks.py", line 56, in GetHighlight
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ffreodasilva/opt/miniconda3/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ffreodasilva/opt/miniconda3/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 679, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/ffreodasilva/opt/miniconda3/lib/python3.12/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ffreodasilva/opt/miniconda3/lib/python3.12/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/ffreodasilva/opt/miniconda3/lib/python3.12/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by DethMetalz69** [comment]
I am getting that too so I think it has to do with that specific call

**Comment by Anil-matcha** [comment]
It's fixed now
