### ISSUE TITLE
error on python main.py

### ISSUE THREAD

**Issue by grmkris** [SamurAIGPT/AI-Youtube-Shorts-Generator#16]
Traceback (most recent call last):
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/main.py", line 4, in <module>
    from Components.LanguageTasks import GetHighlight
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/Components/LanguageTasks.py", line 6, in <module>
    client = OpenAI(
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/venv/lib/python3.9/site-packages/openai/_client.py", line 123, in __init__
    super().__init__(
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/venv/lib/python3.9/site-packages/openai/_base_client.py", line 844, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/venv/lib/python3.9/site-packages/openai/_base_client.py", line 742, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'proxies'

AI-Youtube-Shorts-Generator git:main*

did:
pip install
add openai apikey

**Comment by grmkris** [comment]
solved by updating to openai==1.55.3

**Comment by grmkris** [comment]
new error at the end:


```
Traceback (most recent call last):
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/main.py", line 32, in <module>
    crop_to_vertical("Out.mp4", croped)
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/Components/FaceCrop.py", line 8, in crop_to_vertical
    detect_faces_and_speakers(input_video_path, "DecOut.mp4")
  File "/Users/.../Code/AI-Youtube-Shorts-Generator/Components/Speaker.py", line 110, in detect_faces_and_speakers
    Frames.append([x, y, x1, y1])
UnboundLocalError: local variable 'x' referenced before assignment

AI-Youtube-Shorts-Generator git:main*  375s
```

**Comment by knussear** [comment]
I'm getting this same error
Traceback (most recent call last):
  File "/home/knussear/AI-Youtube-Shorts-Generator/main.py", line 4, in <module>
    from Components.LanguageTasks import GetHighlight
  File "/home/knussear/AI-Youtube-Shorts-Generator/Components/LanguageTasks.py", line 6, in <module>
    client = OpenAI(
  File "/home/knussear/.local/lib/python3.10/site-packages/openai/_client.py", line 123, in __init__
    super().__init__(
  File "/home/knussear/.local/lib/python3.10/site-packages/openai/_base_client.py", line 844, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/home/knussear/.local/lib/python3.10/site-packages/openai/_base_client.py", line 742, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by 47thommy** [comment]
did anyone manage to run it successfully

**Comment by ddayto21** [comment]
> new error at the end:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/.../Code/AI-Youtube-Shorts-Generator/main.py", line 32, in <module>
>     crop_to_vertical("Out.mp4", croped)
>   File "/Users/.../Code/AI-Youtube-Shorts-Generator/Components/FaceCrop.py", line 8, in crop_to_vertical
>     detect_faces_and_speakers(input_video_path, "DecOut.mp4")
>   File "/Users/.../Code/AI-Youtube-Shorts-Generator/Components/Speaker.py", line 110, in detect_faces_and_speakers
>     Frames.append([x, y, x1, y1])
> UnboundLocalError: local variable 'x' referenced before assignment
> 
> AI-Youtube-Shorts-Generator git:main*  375s
> ```

The error `TypeError: __init__() got an unexpected keyword argument 'proxies'` happens because the openai library no longer uses the OpenAI client directly for API calls. 

### Upgrade the openai library
You can address the issue by upgrading the `openai` library to the latest version:

```bash
pip install --upgrade openai
```

### Update the code to match new OpenAI client

Replace this line:
```python
client = OpenAI(api_key=os.getenv("OPENAI_API"))
```

with this line:

```python
openai.api_key = os.getenv("OPENAI_API")
```

This should resolve the issue! Let me know if you face anything else. @47thommy  @knussear knussear

> I'm getting this same error Traceback (most recent call last): File "/home/knussear/AI-Youtube-Shorts-Generator/main.py", line 4, in from Components.LanguageTasks import GetHighlight File "/home/knussear/AI-Youtube-Shorts-Generator/Components/LanguageTasks.py", line 6, in client = OpenAI( File "/home/knussear/.local/lib/python3.10/site-packages/openai/_client.py", line 123, in **init** super().**init**( File "/home/knussear/.local/lib/python3.10/site-packages/openai/_base_client.py", line 844, in **init** self._client = http_client or SyncHttpxClientWrapper( File "/home/knussear/.local/lib/python3.10/site-packages/openai/_base_client.py", line 742, in **init** super().**init**(**kwargs) TypeError: Client.**init**() got an unexpected keyword argument 'proxies'

**Comment by Anil-matcha** [comment]
@ddayto21 Thanks for sharing, have merged your request
