### ISSUE TITLE
Doesn't Work for python version 3.12

### ISSUE THREAD

**Issue by BatScript** [SamurAIGPT/AI-Youtube-Shorts-Generator#5]
library issues detetcted when tried installing on python 3.12.

```
Collecting numpy==1.22.0 (from -r requirements.txt (line 5))
  Using cached numpy-1.22.0.zip (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/mohit/Documents/Personal/AI-Youtube-Shorts-Generator/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mohit/Documents/Personal/AI-Youtube-Shorts-Generator/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mohit/Documents/Personal/AI-Youtube-Shorts-Generator/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/mohit/Documents/Personal/AI-Youtube-Shorts-Generator/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/vm/_xqhytxs5ys8pkxkff902rxw0000gn/T/pip-build-env-6uwbphmp/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/vm/_xqhytxs5ys8pkxkff902rxw0000gn/T/pip-build-env-6uwbphmp/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/vm/_xqhytxs5ys8pkxkff902rxw0000gn/T/pip-build-env-6uwbphmp/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```
When tried 1.26 version of numpy, I face another issue. Fixed it by reinstalling openai.
Once library issues were gone, after pasting yt link, it started throwing 400.

```
Enter YouTube video URL: https://www.youtube.com/watch?v=LP1gfUFP4go
An error occurred: HTTP Error 400: Bad Request
Please make sure you have the latest version of pytube and ffmpeg-python installed.
You can update them by running:
pip install --upgrade pytube ffmpeg-python
Also, ensure that ffmpeg is installed on your system and available in your PATH.
```

**Temporary [Fix](https://github.com/SamurAIGPT/AI-Youtube-Shorts-Generator/pull/6)** : 
I have used [pytubefix](https://pypi.org/project/pytubefix/) instead of pytube, it seems to work

**Comment by Anil-matcha** [comment]
Merged the change
